[tool.black]
line-length = 120
force-exclude = 'migrations/'

[tool.isort]
profile = "black"
line_length = 120
skip = ["migrations"]
known_first_party = ["blog", "users"]

[tool.flake8]
max-line-length = 120
ignore = ["E231", "E241"]
per-file-ignores = ["__init__.py:F401"]
exclude = ["*/migrations/*"]