# Generated by Django 5.2.3 on 2025-07-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, verbose_name='Link')),
                ('short_url_hash', models.CharField(blank=True, help_text='Only last letters without host', max_length=512, null=True, verbose_name='Short link')),
            ],
        ),
    ]
